### ISSUE TITLE
Coverage computation fails with unhandled exception

### ISSUE THREAD

**Issue by 0xbf00** [0xbf00/macos-sandbox-coverage#2]
It is currently not possible to invoke `sandbox_coverage.py` on `Calculator.app` (and probably other apps) on 10.14.6. Is this intended behaviour (due to more explicit error-handling)?

```sh
macos-sandbox-coverage $ ./sandbox_coverage.py --app /Applications/Calculator.app > output.json
  0 % matching rules
Failed to re-check log entry #513:
  Log:       {"action":"allow","argument":"IGAccelDevice","operation":"iokit-open"}
  Last Rule: {"action":"allow","filters":[{"arguments":[{"type":"string","value":"com.apple.backgroundtaskmanagementagent"}],"name":"global-name"}],"operations":["mach-lookup"]}

Traceback (most recent call last):
  File "./sandbox_coverage.py", line 108, in <module>
    main()
  File "./sandbox_coverage.py", line 87, in main
    success, state = perform_matching(state)
  File "/Users/jakob/Programming/macos-sandbox-coverage/sblogs/match.py", line 131, in perform_matching
    [selected_logs[idx] for idx in selected_idxs],
  File "/Users/jakob/Programming/macos-sandbox-coverage/sblogs/match.py", line 37, in get_matches_for_profile
    sandbox_check.check_returncode()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 444, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['/Users/jakob/Programming/macos-sandbox-coverage/matching-core/build/bin/matcher']' returned non-zero exit status 1.
```

**Comment by blochberger** [comment]
It was not intentional to break compatibility with 10.14.6. The underlaying problem is, that some `IOKit` client classes were not mapped to their service, which we might not have noticed without explicit error handling.

Instead of using a pre-computed list, we could integrate [iokit-utils](https://github.com/Siguza/iokit-utils) and calculate the services on demand.

**Comment by 0xbf00** [comment]
Thanks! Works perfectly now :)
